### ISSUE TITLE
syntax error in show method for sightings controller

### ISSUE THREAD

**Issue by richie1982** [learn-co-curriculum/js-rails-as-api-rendering-related-object-data-in-json#2]
def show
        @sighting = Sighting.find(params[:id])
        render json: @sightings.to_json(:include => {:bird => {:only => [:name, :species]},:location => {:only => [:latitude, :longitude]}}
end

leaves a syntax error- 'unexpected end'

**Comment by maxwellbenton** [comment]
Hi @richie1982,

Thank you for spotting this and opening this issue. Looks like there was a typo in the `to_json` statement. We've updated the code snippet and corrected this error and believe the issue is resolved.

Thank you for contributing to a learn.co lesson!
