### ISSUE TITLE
I cannot fork this lab

### ISSUE THREAD

**Issue by endyranaudo** [learn-co-curriculum/js-rails-as-api-rendering-related-object-data-in-json#3]
Hi, for some reason I cannot fork this lab. Can you help me?
Thanks

**Comment by rrcobb** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via a quick edit, or bugs with the Learn platform (such as lights not turning green or IDE issues).

In fact, there's a great article about this very issue over in the Learn Help Center. Check it out! 🎉

If you still require assistance after reading the Help Center article, pop into Ask a Question (AAQ), where the Technical Coaches (on supported tracks) and fellow community members can provide additional help. For some tips on how to take full advantage of AAQ, check out this helpful article in the Learn Help Center.

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
